version: '3'  
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  fastapi:
    build: 
      context: .
      dockerfile: Dockerfile-fastapi
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    volumes:
      - ./main.py:/app/main.py
  web:
    build: 
      context: .
      dockerfile: Dockerfile-django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - fastapi
      - db